name: Bump core
on: 
 schedule:
   - cron: 0 18 * * *
 workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Bump k3s 🔧
      run: |
           sudo -E bash ./.github/bump_core.sh
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}
        push-to-fork: ci-forks/provider-c3os
        commit-message: ":arrow_up: Update k3s"
        signoff: true
        title: ":arrow_up: Kairos core image bump"
        body: "Update of the Kairos core image tag"
