name: Bump k3s
on: 
 schedule:
   - cron: 0 18 * * *
 workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Bump k3s 🔧
      run: |
           sudo -E bash ./.github/bump_k3s_versions.sh
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        signoff: true
        token: ${{ secrets.PAT_TOKEN }}
        push-to-fork: ci-forks/provider-c3os
        commit-message: ":arrow_up: Update k3s"
        title: "K3s versions bump"
        body: "Keep track of stable releases"
